/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2024-12-22 11:26:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1709948090000L));
    _jspx_dependants.put("jar:file:/D:/EclipseSSM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ssm_project/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1054243570000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\" />\r\n");
      out.write("<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("<style>\r\n");
      out.write("	/* 购物车容器样式 */\r\n");
      out.write("	.cart_table {\r\n");
      out.write("		width:80%;\r\n");
      out.write("	    margin: 20px auto;\r\n");
      out.write("	    padding: 10px;\r\n");
      out.write("	    border: 1px solid #ddd;\r\n");
      out.write("	    border-radius: 5px;\r\n");
      out.write("	    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	    background-color: #fff;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 购物车标题 */\r\n");
      out.write("	.cart h6 {\r\n");
      out.write("	    font-size: 20px;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	    color: #fff;\r\n");
      out.write("	    background-color: #EDCDEE;\r\n");
      out.write("	    padding: 10px;\r\n");
      out.write("	    text-align: center;\r\n");
      out.write("	    margin: 0;\r\n");
      out.write("	    border-radius: 5px 5px 0 0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 表格整体样式 */\r\n");
      out.write("	.cart table {\r\n");
      out.write("	    width: 90%;\r\n");
      out.write("	    border-collapse: collapse;\r\n");
      out.write("	    margin: 15px auto; \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 表头样式 */\r\n");
      out.write("	.cart table th {\r\n");
      out.write("	    background-color: #f9f9f9;\r\n");
      out.write("	    color: #333;\r\n");
      out.write("	    font-size: 16px;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	    padding: 10px;\r\n");
      out.write("	    text-align: center;\r\n");
      out.write("	    border-bottom: 2px solid #ddd;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 表格内容行样式 */\r\n");
      out.write("	.cart table td {\r\n");
      out.write("	    background-color: #fff;\r\n");
      out.write("	    padding: 10px;\r\n");
      out.write("	    text-align: center;\r\n");
      out.write("	    font-size: 14px;\r\n");
      out.write("	    color: #555;\r\n");
      out.write("	    border-bottom: 1px solid #eee;\r\n");
      out.write("	}\r\n");
      out.write("	/* 图片样式 */\r\n");
      out.write("	#cart-img {\r\n");
      out.write("	    width: 80px;\r\n");
      out.write("	    height: 60px;\r\n");
      out.write("	    border-radius: 5px;\r\n");
      out.write("	    margin-bottom: 5px;\r\n");
      out.write("		display: block; /* 使图片成为块级元素 */\r\n");
      out.write("	    margin-left: auto; /* 水平居中 */\r\n");
      out.write("	    margin-right: auto; /* 水平居中 */\r\n");
      out.write("	}\r\n");
      out.write("	/* “继续购物”和“结算中心”样式 */\r\n");
      out.write("	.cart table td img {\r\n");
      out.write("	    vertical-align: middle;\r\n");
      out.write("	    cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart table td:first-child {\r\n");
      out.write("	    text-align: left; /* 继续购物按钮靠左 */\r\n");
      out.write("	    padding-left: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart table td:last-child {\r\n");
      out.write("	    text-align: right; /* 结算中心按钮靠右 */\r\n");
      out.write("	    padding-right: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart table td img {\r\n");
      out.write("	    width: auto;\r\n");
      out.write("	    height: auto;\r\n");
      out.write("	    max-height: 40px; /* 确保图片高度适中 */\r\n");
      out.write("	}\r\n");
      out.write("	/* 商品名称链接样式 */\r\n");
      out.write("	.cart table td a.f6 {\r\n");
      out.write("	    color: #555;\r\n");
      out.write("	    text-decoration: none;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	    transition: color 0.3s ease;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart table td a.f6:hover {\r\n");
      out.write("	    color: #EDCDEE;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 操作按钮样式 */\r\n");
      out.write("	.cart table td a {\r\n");
      out.write("	    color: #E74C3C;\r\n");
      out.write("	    text-decoration: underline;\r\n");
      out.write("	    font-size: 14px;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart table td a:hover {\r\n");
      out.write("	    color: #FF5733;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 响应式优化 */\r\n");
      out.write("	@media (max-width: 768px) {\r\n");
      out.write("	    .cart table td {\r\n");
      out.write("	        font-size: 12px;\r\n");
      out.write("	    }\r\n");
      out.write("	\r\n");
      out.write("	    .cart table td img {\r\n");
      out.write("	        width: 60px;\r\n");
      out.write("	        height: 60px;\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"block box\">\r\n");
      out.write("		<div class=\"blank\"></div>\r\n");
      out.write("		<div id=\"ur_here\">\r\n");
      out.write("			当前位置: <a href=\".\">首页</a>\r\n");
      out.write("			<code> &gt; </code>\r\n");
      out.write("			购物车\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"blank\"></div>\r\n");
      out.write("	<div class=\"cart_table\">\r\n");
      out.write("		<div class=\"cart\">\r\n");
      out.write("			<h6>\r\n");
      out.write("				<span>购物车</span>\r\n");
      out.write("			</h6>\r\n");
      out.write("			<!-- 表单提交的数据发送到Controller：index/deletecart.action -->\r\n");
      out.write("			<form action=\"index/deletecart.action\" method=\"post\">\r\n");
      out.write("				<!-- 购物车信息的表格 -->\r\n");
      out.write("				<table width=\"99%\" align=\"center\" border=\"0\" cellpadding=\"5\" cellspacing=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th bgcolor=\"#ffffff\">商品名称</th>\r\n");
      out.write("						<th bgcolor=\"#ffffff\">价格</th>\r\n");
      out.write("						<th bgcolor=\"#ffffff\">数量</th>\r\n");
      out.write("						<th bgcolor=\"#ffffff\">日期</th>\r\n");
      out.write("						<th bgcolor=\"#ffffff\">操作</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /users/cart.jsp(160,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /users/cart.jsp(160,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("cart");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("						<tr>\r\n");
              out.write("							<td bgcolor=\"#ffffff\" align=\"center\" style=\"width: 300px;\">\r\n");
              out.write("								<a href=\"index/detail.action?id=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.goodsid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\"target=\"_blank\">\r\n");
              out.write("									<img id=\"cart-img\" src=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.image }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" border=\"0\" title=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.goodsname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" />\r\n");
              out.write("								</a> \r\n");
              out.write("								<br /> \r\n");
              out.write("								<a href=\"index/detail.action?id=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.goodsid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" target=\"_blank\" class=\"f6\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.goodsname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</a>\r\n");
              out.write("							</td>\r\n");
              out.write("							<td align=\"center\" bgcolor=\"#ffffff\">￥");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("元</td>\r\n");
              out.write("							<td align=\"center\" bgcolor=\"#ffffff\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("							<td align=\"center\" bgcolor=\"#ffffff\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.addtime }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("							<!-- 前端以 URL 查询参数的形式传递 id -->\r\n");
              out.write("							<td bgcolor=\"#ffffff\">\r\n");
              out.write("								<a\r\n");
              out.write("								href=\"javascript:if (confirm('您确实要移出购物车吗？')) location.href='");
              out.print(basePath);
              out.write("index/deletecart.action?id=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.cartid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("'; \"\r\n");
              out.write("								>移除\r\n");
              out.write("								</a>\r\n");
              out.write("							</td>\r\n");
              out.write("						</tr>\r\n");
              out.write("					");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("				</table>\r\n");
      out.write("				\r\n");
      out.write("				<!-- 继续购物和结算中心 -->\r\n");
      out.write("				<table width=\"99%\" align=\"center\" border=\"0\" cellpadding=\"5\" cellspacing=\"0\" bgcolor=\"#dddddd\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td bgcolor=\"#ffffff\"><a href=\"index.jsp\">\r\n");
      out.write("						<img src=\"asset/images/continue.png\"\r\n");
      out.write("								alt=\"continue\" /> </a></td>\r\n");
      out.write("						<td bgcolor=\"#ffffff\" align=\"right\"><a href=\"index/preCheckout.action\">\r\n");
      out.write("						<img src=\"asset/images/checkout.png\" alt=\"checkout\" /> </a></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"blank\"></div>\r\n");
      out.write("		<div class=\"blank5\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
