/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2024-12-22 11:19:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1709948090000L));
    _jspx_dependants.put("jar:file:/D:/EclipseSSM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ssm_project/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1054243570000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // 动态获取项目的根路径
    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!-- 引入样式文件 -->\r\n");
      out.write("<link href=\"themes/ecmoban_dangdang/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- 顶部横幅 -->\r\n");
      out.write("<img src=\"asset/images/top_bg2.jpg\" alt=\"顶部横幅\" style=\"height: 80px; width: 100%;\" />\r\n");
      out.write("<!-- 头部区域 -->\r\n");
      out.write("<div class=\"clearfix\">\r\n");
      out.write("    <div class=\"block header\">\r\n");
      out.write("        <div class=\"top\" style=\"display: flex; align-items: center; padding-left: 20px; height: 100%;\">\r\n");
      out.write("            <!-- 网站LOGO -->\r\n");
      out.write("            <a href=\"index.jsp\" style=\"font-size: 30px; font-weight: bold; text-align: center; color: #b027b2; letter-spacing: 2px;\">\r\n");
      out.write("                <img src=\"asset/images/logo.jpg\" alt=\"网站LOGO\" style=\"height: 80px;\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <!-- 导航菜单 -->\r\n");
      out.write("            <div class=\"head_r\" style=\"display: flex; align-items: center;\">\r\n");
      out.write("                <div class=\"menu\" style=\"width: 500px; margin-top: 33px; font-size: 15px;\">\r\n");
      out.write("                    <a href=\"index.jsp\" rel=\"nofollow\">首页</a>\r\n");
      out.write("                    <a href=\"index/recommend.action\" rel=\"nofollow\">热销推荐</a>\r\n");
      out.write("                    <a href=\"index/special.action\" rel=\"nofollow\">特价促销</a>\r\n");
      out.write("                    <a href=\"index/all.action\" rel=\"nofollow\">查看所有</a>\r\n");
      out.write("                    <a href=\"index/article.action\" rel=\"nofollow\">新闻公告</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 搜索框 -->\r\n");
      out.write("				<div class=\"top_search\" style=\"display: flex; align-items: center; margin-top: 5px;\">\r\n");
      out.write("				    <form action=\"index/query.action\" method=\"post\" id=\"searchForm\" name=\"searchForm\" style=\"display: flex; align-items: center;\">\r\n");
      out.write("				        <!-- 搜索框 -->\r\n");
      out.write("				        <input \r\n");
      out.write("				            name=\"name\" \r\n");
      out.write("				            type=\"text\" \r\n");
      out.write("				            id=\"keyword\" \r\n");
      out.write("				            class=\"keyword\" \r\n");
      out.write("				            placeholder=\"搜索商品...\" \r\n");
      out.write("				            style=\"height: 36px; padding: 0 10px; font-size: 14px; border: 1px solid #ddd; border-radius: 4px; flex: 1;\" \r\n");
      out.write("				        />\r\n");
      out.write("				        <!-- 搜索按钮 -->\r\n");
      out.write("				        <input \r\n");
      out.write("				            value=\"搜 索\" \r\n");
      out.write("				            id=\"searchbtn\" \r\n");
      out.write("				            type=\"submit\" \r\n");
      out.write("				            style=\"height: 38px; margin-left: 8px; background: #b027b2; color: white; font-size: 16px; border: none; border-radius: 4px; padding: 0 20px; cursor: pointer;\" \r\n");
      out.write("				        />\r\n");
      out.write("				    </form>\r\n");
      out.write("				</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 导航栏 -->\r\n");
      out.write("<div style=\"clear: both;\"></div>\r\n");
      out.write("<div class=\"menu_box clearfix\">\r\n");
      out.write("    <div class=\"block\" style=\"display: flex;\">\r\n");
      out.write("        <!-- 合作伙伴LOGO -->\r\n");
      out.write("        <div style=\"width: 730px;\">\r\n");
      out.write("            <img width=\"83\" height=\"37\" src=\"https://image2.cn10.cn/upload/images/20220602/17552766122_200x90.png\" alt=\"合作伙伴1\">\r\n");
      out.write("            <img width=\"83\" height=\"37\" src=\"https://image2.cn10.cn/upload/images/20220511/18030956843_200x90.png\" alt=\"合作伙伴2\">\r\n");
      out.write("            <img width=\"83\" height=\"37\" src=\"https://image2.cn10.cn/upload/images/20220506/18011886028_200x90.png\" alt=\"合作伙伴3\">\r\n");
      out.write("            <img width=\"83\" height=\"37\" src=\"https://image2.cn10.cn/upload/images/20220511/18030597711_200x90.png\" alt=\"合作伙伴4\">\r\n");
      out.write("            <img width=\"83\" height=\"37\" src=\"asset/images/5.png\" alt=\"合作伙伴5\">\r\n");
      out.write("            <img width=\"83\" height=\"37\" src=\"https://image2.cn10.cn/upload/images/20220511/18031023475_200x90.png\" alt=\"合作伙伴6\">\r\n");
      out.write("            <img width=\"83\" height=\"37\" src=\"https://image2.cn10.cn/upload/images/20220511/18030671680_200x90.png\" alt=\"合作伙伴7\">\r\n");
      out.write("            <img width=\"83\" height=\"37\" src=\"https://image2.cn10.cn/upload/images/20220511/18030961893_200x90.png\" alt=\"合作伙伴8\">\r\n");
      out.write("            <img width=\"83\" height=\"37\" src=\"https://image.maigoo.com/upload/images/20220523/15255552825_200x90.png\" alt=\"合作伙伴9\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 用户登录状态 -->\r\n");
      out.write("        <div style=\"text-align: right;\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /users/header.jsp(74,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <a href=\"index/preLogin.action\" rel=\"nofollow\">用户登录</a>\r\n");
          out.write("                <a href=\"index/preReg.action\" rel=\"nofollow\">用户注册</a>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /users/header.jsp(78,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <a href=\"#\" rel=\"nofollow\">欢迎您：");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("                <a href=\"index/cart.action\" rel=\"nofollow\">购物车</a>\r\n");
          out.write("                <a href=\"index/usercenter.action\" rel=\"nofollow\">用户中心</a>\r\n");
          out.write("                <a href=\"index/exit.action\" rel=\"nofollow\">退出登录</a>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
