/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2024-12-22 13:49:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class pay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1709948090000L));
    _jspx_dependants.put("jar:file:/D:/EclipseSSM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ssm_project/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1054243570000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\" />\r\n");
      out.write("<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* 外层容器样式 */\r\n");
      out.write(".pay {\r\n");
      out.write("    width: 50%;\r\n");
      out.write("    margin: 20px auto;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 头部样式 */\r\n");
      out.write(".pay-header {\r\n");
      out.write("    background-color: #EDCDEE;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border-radius: 8px 8px 0 0;\r\n");
      out.write("    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pay-header h1 {\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 标签导航样式 */\r\n");
      out.write(".tab-head {\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("    border-bottom: 1px solid #ddd;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab-head h2 {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    color: #555;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab-head h2.selected {\r\n");
      out.write("    color: #EDCDEE;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    border-bottom: 2px solid #EDCDEE;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 表单内容样式 */\r\n");
      out.write(".content {\r\n");
      out.write("    margin: 20px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content dt {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content dd {\r\n");
      out.write("    margin: 0 0 20px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content input[type=\"text\"],\r\n");
      out.write(".content input[type=\"number\"],\r\n");
      out.write(".content input[type=\"email\"] {\r\n");
      out.write("    width: 95%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    transition: border 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content input[type=\"text\"]:focus,\r\n");
      out.write(".content input[type=\"number\"]:focus,\r\n");
      out.write(".content input[type=\"email\"]:focus {\r\n");
      out.write("    border-color: #EDCDEE;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 提交按钮样式 */\r\n");
      out.write(".new-btn-login {\r\n");
      out.write("    background-color: #EDCDEE;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    padding: 12px 25px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".new-btn-login:hover {\r\n");
      out.write("    background-color: #d2a9c7;\r\n");
      out.write("    box-shadow: 0 6px 10px rgba(0, 0, 0, 0.15);\r\n");
      out.write("    transform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".new-btn-login:active {\r\n");
      out.write("    background-color: #b890aa;\r\n");
      out.write("    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    transform: translateY(2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 提示文字样式 */\r\n");
      out.write(".note-help {\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    color: #888;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 响应式优化 */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    .pay {\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .content input[type=\"text\"],\r\n");
      out.write("    .content input[type=\"number\"],\r\n");
      out.write("    .content input[type=\"email\"] {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .new-btn-login {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("js/jquery-1.3.2.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"block box\">\r\n");
      out.write("		<div class=\"blank\"></div>\r\n");
      out.write("		<div id=\"ur_here\">\r\n");
      out.write("			当前位置: <a href=\"");
      out.print(basePath);
      out.write("\">首页</a>\r\n");
      out.write("			<code> &gt; </code>\r\n");
      out.write("			付款\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"blank\"></div>\r\n");
      out.write("	<div class=\"pay\">\r\n");
      out.write("		<header class=\"pay-header\">\r\n");
      out.write("			<h1>付款</h1>\r\n");
      out.write("		</header>\r\n");
      out.write("		<div id=\"pay-main\">\r\n");
      out.write("			<div id=\"tabhead\" class=\"tab-head\">\r\n");
      out.write("				<h2 id=\"tab1\" class=\"selected\" name=\"tab\">付 款</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form autocomplete=\"off\" name=alipayment action=\"index/pay.action\" method=post>\r\n");
      out.write("				<div id=\"body1\" class=\"show\" name=\"divcontent\">\r\n");
      out.write("					<dl class=\"content\">\r\n");
      out.write("						<dt>商户订单号 ：</dt>\r\n");
      out.write("						<dd>\r\n");
      out.write("							<input id=\"WIDout_trade_no\" name=\"WIDout_trade_no\" />\r\n");
      out.write("						</dd>\r\n");
      out.write("						<dt>订单名称 ：</dt>\r\n");
      out.write("						<dd>\r\n");
      out.write("							<input id=\"WIDsubject\" name=\"WIDsubject\" />\r\n");
      out.write("						</dd>\r\n");
      out.write("						<dt>付款金额 ：</dt>\r\n");
      out.write("						<dd>\r\n");
      out.write("							<input id=\"WIDtotal_amount\" name=\"WIDtotal_amount\" />\r\n");
      out.write("						</dd>\r\n");
      out.write("						<dt></dt>\r\n");
      out.write("						<dd id=\"btn-dd\">\r\n");
      out.write("							<span class=\"new-btn-login-sp\">\r\n");
      out.write("								<button id=\"pay\" class=\"new-btn-login\" type=\"submit\" style=\"text-align: center;\">付 款</button> <input\r\n");
      out.write("								type=\"hidden\" name=\"id\" id=\"ordersid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orders.ordersid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input type=\"hidden\" name=\"basepath\"\r\n");
      out.write("								id=\"basepath\" value=\"");
      out.print(basePath);
      out.write("\" />\r\n");
      out.write("							</span> <span class=\"note-help\">如果您点击“付款”按钮，即表示您同意该次的执行操作。</span>\r\n");
      out.write("						</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("	var tabs = document.getElementsByName('tab');\r\n");
      out.write("	var contents = document.getElementsByName('divcontent');\r\n");
      out.write("\r\n");
      out.write("	(function changeTab(tab) {\r\n");
      out.write("		for (var i = 0, len = tabs.length; i < len; i++) {\r\n");
      out.write("			tabs[i].onmouseover = showTab;\r\n");
      out.write("		}\r\n");
      out.write("	})();\r\n");
      out.write("\r\n");
      out.write("	function showTab() {\r\n");
      out.write("		for (var i = 0, len = tabs.length; i < len; i++) {\r\n");
      out.write("			if (tabs[i] === this) {\r\n");
      out.write("				tabs[i].className = 'selected';\r\n");
      out.write("				contents[i].className = 'show';\r\n");
      out.write("			} else {\r\n");
      out.write("				tabs[i].className = '';\r\n");
      out.write("				contents[i].className = 'tab-content';\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function GetDateNow() {\r\n");
      out.write("		var vNow = new Date();\r\n");
      out.write("		var sNow = \"\";\r\n");
      out.write("		sNow += String(vNow.getFullYear());\r\n");
      out.write("		sNow += String(vNow.getMonth() + 1);\r\n");
      out.write("		sNow += String(vNow.getDate());\r\n");
      out.write("		sNow += String(vNow.getHours());\r\n");
      out.write("		sNow += String(vNow.getMinutes());\r\n");
      out.write("		sNow += String(vNow.getSeconds());\r\n");
      out.write("		sNow += String(vNow.getMilliseconds());\r\n");
      out.write("		document.getElementById(\"WIDout_trade_no\").value = sNow;\r\n");
      out.write("		document.getElementById(\"WIDsubject\").value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orders.ordercode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		document.getElementById(\"WIDtotal_amount\").value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orders.total}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("	}\r\n");
      out.write("	GetDateNow();\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
