/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2024-12-22 08:35:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class userinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1709948090000L));
    _jspx_dependants.put("jar:file:/D:/EclipseSSM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ssm_project/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1054243570000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"zh_CN\">\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\" />\r\n");
      out.write("<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.3.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/users.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/selimage.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("My97DatePicker/WdatePicker.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("/* 外层容器样式 */\r\n");
      out.write(".personal {\r\n");
      out.write("    width: 80%;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 表单标题样式 */\r\n");
      out.write(".personal-info-table h5 {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color: #EDCDEE;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 表格样式 */\r\n");
      out.write(".personal-info-table table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 表格单元格样式 */\r\n");
      out.write(".personal-info-table table td {\r\n");
      out.write("    padding: 10px 15px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 表格标签左对齐和右对齐 */\r\n");
      out.write(".personal-info-table table td:first-child {\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    width: 30%;\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".personal-info-table table td:last-child {\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 输入框样式 */\r\n");
      out.write(".inputBg {\r\n");
      out.write("    width: 80%;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    transition: border 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inputBg:focus {\r\n");
      out.write("    border-color: #EDCDEE;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 单选按钮样式 */\r\n");
      out.write(".personal-info-table input[type=\"radio\"] {\r\n");
      out.write("    margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub {\r\n");
      out.write("    background-color: #EDCDEE; /* 按钮背景色 */\r\n");
      out.write("    color: #fff; /* 按钮文字颜色 */\r\n");
      out.write("    font-size: 16px; /* 文字大小 */\r\n");
      out.write("    font-weight: bold; /* 加粗文字 */\r\n");
      out.write("    padding: 10px 20px; /* 按钮内边距 */\r\n");
      out.write("    border: none; /* 去除边框 */\r\n");
      out.write("    border-radius: 5px; /* 按钮圆角 */\r\n");
      out.write("    cursor: pointer; /* 鼠标样式为手型 */\r\n");
      out.write("    transition: all 0.3s ease; /* 添加过渡动画 */\r\n");
      out.write("    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* 按钮阴影 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"block box\">\r\n");
      out.write("		<div class=\"blank\"></div>\r\n");
      out.write("		<div id=\"ur_here\">\r\n");
      out.write("			当前位置: <a href=\"index/index.action\">首页</a>\r\n");
      out.write("			<code> &gt; </code>\r\n");
      out.write("			用户中心\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"blank\"></div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"block clearfix\">\r\n");
      out.write("		<div class=\"AreaL\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "usermenu.jsp", out, false);
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"AreaR\">\r\n");
      out.write("			<div class=\"personal\">\r\n");
      out.write("				<div class=\"personal-box\">\r\n");
      out.write("					<div class=\"personal-info-table\">\r\n");
      out.write("						<h5>\r\n");
      out.write("							<span>个人资料</span>\r\n");
      out.write("						</h5>\r\n");
      out.write("						<div class=\"blank\"></div>\r\n");
      out.write("						<form name=\"formEdit\" action=\"index/personal.action\" method=\"post\" onsubmit=\"return userEdit()\">\r\n");
      out.write("							<table width=\"100%\" border=\"0\" cellpadding=\"5\" cellspacing=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td align=\"right\" bgcolor=\"#FFFFFF\">用户名：</td>\r\n");
      out.write("									<td align=\"left\" bgcolor=\"#FFFFFF\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.users.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" name=\"username\"\r\n");
      out.write("										id=\"username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.users.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input type=\"hidden\" name=\"password\" id=\"password\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.users.password }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input type=\"hidden\" name=\"usersid\" id=\"usersid\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.users.usersid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><input type=\"hidden\" name=\"regdate\" id=\"regdate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.users.regdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td align=\"right\" bgcolor=\"#FFFFFF\">姓名：</td>\r\n");
      out.write("									<td align=\"left\" bgcolor=\"#FFFFFF\"><input name=\"realname\" type=\"text\" size=\"25\" class=\"inputBg\" id=\"realname\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.users.realname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td align=\"right\" bgcolor=\"#FFFFFF\">性别：</td>\r\n");
      out.write("									<td  align=\"left\" bgcolor=\"#FFFFFF\"><input type=\"radio\" name=\"sex\" value=\"男\" title=\"男\" id=\"sex\" checked />男&nbsp;&nbsp;&nbsp;<input\r\n");
      out.write("										type=\"radio\" name=\"sex\" value=\"女\" title=\"女\" id=\"sex\" />女</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td align=\"right\" bgcolor=\"#FFFFFF\">出生日期：</td>\r\n");
      out.write("									<td align=\"left\" bgcolor=\"#FFFFFF\"><input name=\"birthday\" type=\"text\" size=\"25\" class=\"inputBg\" id=\"birthday\"\r\n");
      out.write("										onclick=\"WdatePicker()\" readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.users.birthday }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td align=\"right\" bgcolor=\"#FFFFFF\">联系方式：</td>\r\n");
      out.write("									<td align=\"left\" bgcolor=\"#FFFFFF\"><input name=\"contact\" type=\"text\" size=\"25\" class=\"inputBg\" id=\"contact\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.users.contact }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td colspan=\"2\" align=\"center\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("								        <input type=\"submit\" value=\"确认修改\" id=\"sub\" />\r\n");
      out.write("								    </td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</table>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"blank\"></div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
