/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2024-12-22 09:47:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addadmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1709948090000L));
    _jspx_dependants.put("jar:file:/D:/EclipseSSM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ssm_project/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1054243570000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "check_logstate.jsp", out, false);
      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"zh_CN\">\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>欢迎使用后台管理系统</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"asset/css/pintuer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"asset/css/admin.css\">\r\n");
      out.write("<script src=\"asset/js/jquery.js\"></script>\r\n");
      out.write("<script src=\"asset/js/pintuer.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/admin.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/selimage.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("My97DatePicker/WdatePicker.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("/* 外层容器样式 */\r\n");
      out.write(".add-admin-panel {\r\n");
      out.write("    width: 70%;\r\n");
      out.write("    margin: 20px auto;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    font-family: Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 标题样式 */\r\n");
      out.write(".add-admin-panel-title {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color: #EDCDEE;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border-radius: 8px 8px 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 表单内容样式 */\r\n");
      out.write(".add-admin-panel-content {\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 表单组样式 */\r\n");
      out.write(".form-group {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 标签部分样式 */\r\n");
      out.write(".label {\r\n");
      out.write("    width: 20%;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    padding-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 输入框容器样式 */\r\n");
      out.write(".field {\r\n");
      out.write("    width: 80%;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 输入框样式 */\r\n");
      out.write(".input {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    transition: border 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input:focus {\r\n");
      out.write("    border-color: #4CAF50;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 提交按钮样式 */\r\n");
      out.write("button[type=\"submit\"] {\r\n");
      out.write("    background-color: #EDCDEE;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 响应式优化 */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    .add-admin-panel {\r\n");
      out.write("        width: 90%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        align-items: flex-start;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .label {\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        padding-right: 0;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .field {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .input {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    button[type=\"submit\"] {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"add-admin-panel\" style=\"width: 70%; margin: 0 auto;\">\r\n");
      out.write("		<div class=\"add-admin-panel-title\" id=\"add\">\r\n");
      out.write("			<strong>新增管理员信息</strong>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"add-admin-panel-content\">\r\n");
      out.write("			<!-- 表单数据发送给Controller：admin/addAdmin.action -->\r\n");
      out.write("			<form method=\"post\" class=\"form-x\" action=\"admin/addAdmin.action\" name=\"myform\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"label\">\r\n");
      out.write("						<label>用户名</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"field\">\r\n");
      out.write("						<input type=\"text\" name=\"username\" class=\"input w150\" id=\"username\" placeholder=\"请输入用户名\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"label\">\r\n");
      out.write("						<label>密码</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"field\">\r\n");
      out.write("						<input type=\"password\" name=\"password\" class=\"input w150\" id=\"password\" placeholder=\"请输入密码\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"label\">\r\n");
      out.write("						<label>姓名</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"field\">\r\n");
      out.write("						<input type=\"text\" name=\"realname\" class=\"input w150\" id=\"realname\" placeholder=\"请输入姓名\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"label\">\r\n");
      out.write("						<label>联系方式</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"field\">\r\n");
      out.write("						<input type=\"text\" name=\"contact\" class=\"input w150\" id=\"contact\" placeholder=\"请输入联系方式\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"label\">\r\n");
      out.write("						<label></label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"field\">\r\n");
      out.write("						<button type=\"submit\">提交保存</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
